
(function(){
'use strict';
const $=id=>document.getElementById(id),{META,sortTrace,searchGrid}=globalThis.AlgoShelf;
const rows=15,cols=25;let mode='sort',sortAlgorithm='bubble',pathAlgorithm='bfs',values=[42,16,73,28,91,55,12,64,36,85,23,48,99,31,67,8],walls=new Set(),start=176,goal=198,tool='wall',frames=[],cursor=0,timer=null,running=false,graphResult=null,drawing=false,lastPaint=-1;
const sortKeys=['bubble','selection','insertion','quick','merge'],pathKeys=['bfs','dfs'];
const pace=[900,480,220,85,25],paceText=['0.25×','0.5×','1×','2.5×','9×'];
function stop(){clearTimeout(timer);timer=null;running=false;}
function setMeta(){const key=$('algorithm').value,m=META[key];$('infoTitle').textContent=m.name;$('description').textContent=m.description;$('time').textContent=m.time;$('space').textContent=m.space;$('note').textContent=m.note;$('timeLabel').textContent=mode==='sort'?'Average time':'Time';$('pseudocode').replaceChildren(...m.code.map(line=>{const li=document.createElement('li');li.textContent=line;return li;}));}
function prepare(){stop();cursor=0;if(mode==='sort'){frames=sortTrace(values,$('algorithm').value);}else{graphResult=searchGrid(rows,cols,walls,start,goal,$('algorithm').value);frames=[{kind:'ready',message:'Draw walls or press Visualize to explore the grid.',line:-1}];graphResult.visited.forEach((cell,i)=>frames.push({kind:'visit',cell,count:i+1,line:1,message:'Visit row '+(Math.floor(cell/cols)+1)+', column '+(cell%cols+1)+'.'}));graphResult.path.forEach((cell,i)=>frames.push({kind:'path',cell,pathCount:i+1,line:2,message:'Trace route: '+i+' edge'+(i===1?'':'s')+' from start.'}));frames.push({kind:'end',line:-1,message:graphResult.found?'Goal reached. Route length: '+(graphResult.path.length-1)+' steps. '+($('algorithm').value==='bfs'?'This is a shortest route.':'DFS does not guarantee a shortest route.'):'No route found. Erase some walls and try again.'});}render();}
function renderBooks(frame){const shelf=$('shelf'),fixed=new Set(frame.fixed);shelf.classList.toggle('dense',values.length>25);shelf.replaceChildren(...frame.values.map((value,i)=>{const div=document.createElement('div');div.className='book'+(fixed.has(i)?' done':'')+(frame.active.includes(i)?' active':'')+(frame.pivot===i?' pivot':'');div.style.height=(20+value/99*78)+'%';const n=document.createElement('b'),index=document.createElement('em');n.textContent=value;index.textContent=String(i+1).padStart(2,'0');div.append(n,index);div.title='Position '+(i+1)+': '+value;shelf.append(div);return div;}));shelf.setAttribute('aria-label','Values: '+frame.values.join(', ')+'. '+frame.message);}
function buildGrid(){const grid=$('grid');grid.replaceChildren(...Array.from({length:rows*cols},(_,i)=>{const b=document.createElement('button');b.className='cell';b.dataset.cell=i;b.tabIndex=i===start?0:-1;return b;}));}
function renderGrid(){const seen=new Set(),path=new Set();for(let i=1;i<=cursor;i++){const f=frames[i];if(f.kind==='visit')seen.add(f.cell);if(f.kind==='path')path.add(f.cell);}for(const b of $('grid').children){const i=Number(b.dataset.cell);let kind=walls.has(i)?'wall':path.has(i)?'path':seen.has(i)?'visited':'';if(i===start)kind='start';if(i===goal)kind='goal';b.className='cell '+kind;b.textContent=i===start?'S':i===goal?'G':'';b.setAttribute('aria-label','Row '+(Math.floor(i/cols)+1)+', column '+(i%cols+1)+': '+(kind||'empty'));b.disabled=running;}$('stat1').textContent=seen.size;$('stat2').textContent=path.size?path.size-1:'—';$('stat3').textContent=walls.size;}
function render(){const f=frames[cursor],finished=cursor===frames.length-1;
 $('status').textContent=running?'RUNNING':finished?'COMPLETE':cursor?'PAUSED':'READY';$('play').textContent=running?'Ⅱ Pause':finished?'↻ Replay':cursor?'▶ Resume':'▶ Visualize';$('step').disabled=running||finished;$('back').disabled=running||cursor===0;$('seek').max=frames.length-1;$('seek').value=cursor;$('stepLabel').textContent='Step '+cursor+' / '+(frames.length-1);$('event').textContent=f.message;
 $('event').setAttribute('aria-live',running?'off':'polite');
 for(const el of [$('algorithm'),$('size'),$('pattern'),$('shuffle'),$('numbers'),$('customForm').querySelector('button'),$('randomWalls'),$('clearWalls')])el.disabled=running;
 if(mode==='sort'){renderBooks(f);$('stat1').textContent=f.comparisons;$('stat2').textContent=f.writes;$('stat3').textContent=values.length;}else renderGrid();
 [...$('pseudocode').children].forEach((li,i)=>li.classList.toggle('current',i===f.line));
}
function tick(){if(!running)return;if(cursor<frames.length-1)cursor++;if(cursor===frames.length-1)stop();render();if(running)timer=setTimeout(tick,pace[Number($('speed').value)-1]);}
function play(){if(running){stop();render();return;}if(cursor===frames.length-1)cursor=0;running=true;render();timer=setTimeout(tick,pace[Number($('speed').value)-1]);}
function makeValues(){let count=Number($('size').value),pattern=$('pattern').value;values=Array.from({length:count},()=>Math.floor(Math.random()*99)+1);if(pattern==='duplicates')values=values.map(x=>[15,35,55,75,95][x%5]);if(pattern==='sorted'||pattern==='nearly')values.sort((a,b)=>a-b);if(pattern==='reverse')values.sort((a,b)=>b-a);if(pattern==='nearly'&&count>2){const i=Math.floor(count/2);[values[i],values[i+1]]=[values[i+1],values[i]];}$('sizeValue').textContent=count;prepare();}
function switchMode(next){if(next===mode)return;stop();if(mode==='sort')sortAlgorithm=$('algorithm').value;else pathAlgorithm=$('algorithm').value;mode=next;const isSort=mode==='sort';$('sortTab').setAttribute('aria-pressed',String(isSort));$('pathTab').setAttribute('aria-pressed',String(!isSort));$('sortScene').hidden=!isSort;$('pathScene').hidden=isSort;$('sizeControl').hidden=!isSort;$('patternControl').hidden=!isSort;$('custom').hidden=!isSort;$('shuffle').hidden=!isSort;$('algorithm').replaceChildren(...(isSort?sortKeys:pathKeys).map(key=>{const o=document.createElement('option');o.value=key;o.textContent=META[key].name;return o;}));$('algorithm').value=isSort?sortAlgorithm:pathAlgorithm;$('breadcrumb').textContent=isSort?'Sorting studio':'Pathfinder';$('chapterLabel').textContent=isSort?'01 / ORDER FROM CHAOS':'02 / FIND YOUR WAY';$('chapterNumber').textContent=isSort?'01':'02';$('pageTitle').innerHTML=isSort?'A little order.<br>A lot of understanding.':'Every path begins<br>with a single step.';$('subtitle').textContent=isSort?'Turn a shelf of numbers into a lesson. Pick an algorithm and watch the logic unfold.':'Build a maze, choose a search, and follow the journey from start to goal.';$('stageTitle').textContent=isSort?'The sorting shelf':'The exploration grid';$('stageCaption').textContent=isSort?'Ascending order · values 1–99':'15 × 25 cells · unweighted · four directions';['statLabel1','statLabel2','statLabel3'].forEach((id,i)=>$(id).textContent=(isSort?['COMPARISONS','ARRAY WRITES','BOOKS ON SHELF']:['CELLS VISITED','ROUTE STEPS','WALLS'])[i]);$('tip').textContent=isSort?'Run the same algorithm on a reversed shelf, then an already sorted one. What changes?':'Keep the same walls and compare BFS with DFS. Does exploring fewer cells always mean a shorter route?';setMeta();prepare();}
function paint(cell){if(running||cell===lastPaint)return;lastPaint=cell;if(tool==='start'){if(cell===goal)return;start=cell;walls.delete(cell);}else if(tool==='goal'){if(cell===start)return;goal=cell;walls.delete(cell);}else if(cell!==start&&cell!==goal){if(tool==='erase')walls.delete(cell);else walls.add(cell);}prepare();}
$('sortTab').onclick=()=>switchMode('sort');$('pathTab').onclick=()=>switchMode('path');$('play').onclick=play;$('step').onclick=()=>{stop();cursor=Math.min(cursor+1,frames.length-1);render();};$('back').onclick=()=>{stop();cursor=Math.max(0,cursor-1);render();};$('reset').onclick=()=>{stop();cursor=0;render();};$('seek').oninput=()=>{stop();cursor=Number($('seek').value);render();};$('shuffle').onclick=()=>{for(let i=values.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]];}$('pattern').value='random';prepare();};$('algorithm').onchange=()=>{setMeta();prepare();};$('size').oninput=makeValues;$('pattern').onchange=makeValues;$('speed').oninput=()=>{$('speedValue').textContent=paceText[Number($('speed').value)-1];};
$('customForm').onsubmit=e=>{e.preventDefault();if(running)return;const text=$('numbers').value.trim(),tokens=text.split(',').map(s=>s.trim());if(tokens.length<2||tokens.length>40||tokens.some(s=>!/^\d+$/.test(s)||Number(s)<1||Number(s)>99)){$('inputError').textContent='Use 2–40 whole numbers from 1 to 99, separated by commas.';return;}$('inputError').textContent='';values=tokens.map(Number);$('size').value=values.length;$('sizeValue').textContent=values.length;$('pattern').value='random';prepare();};
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));};
$('randomWalls').onclick=()=>{walls=new Set();for(let i=0;i<rows*cols;i++)if(i!==start&&i!==goal&&Math.random()<.24)walls.add(i);prepare();};$('clearWalls').onclick=()=>{walls.clear();prepare();};
$('grid').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-cell]');if(!b||running)return;e.preventDefault();drawing=true;lastPaint=-1;b.focus();paint(Number(b.dataset.cell));});
document.addEventListener('pointermove',e=>{if(!drawing||running)return;const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-cell]');if(b&&b.parentElement===$('grid'))paint(Number(b.dataset.cell));});
for(const event of ['pointerup','pointercancel'])document.addEventListener(event,()=>{drawing=false;lastPaint=-1;});
$('grid').addEventListener('keydown',e=>{const b=e.target.closest('[data-cell]');if(!b||running)return;const cell=Number(b.dataset.cell),r=Math.floor(cell/cols),c=cell%cols;let next=cell;if(e.key==='ArrowUp'&&r>0)next-=cols;else if(e.key==='ArrowDown'&&r<rows-1)next+=cols;else if(e.key==='ArrowLeft'&&c>0)next--;else if(e.key==='ArrowRight'&&c<cols-1)next++;else if(e.key==='Enter'||e.key===' '){e.preventDefault();lastPaint=-1;paint(cell);return;}else return;e.preventDefault();b.tabIndex=-1;const target=$('grid').children[next];target.tabIndex=0;target.focus();});
window.addEventListener('blur',()=>{drawing=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stop();render();}});
buildGrid();setMeta();prepare();
})();
